export const projects = [
  {
    id: 1,
    title: "JrFood",
    description: "le projet met en avant mes compétences en html, css et javascript )",
    image: "/projects/gestion-pilotage.jpg",
    tags: ["HTML", "CSS", "JavaScript"],
    category: "Front end",
    featured: true,
    liveUrl: "https://jrfood.netlify.app",
    githubUrl: "https://github.com/rye852/Food-project",
    year: "2023",
  },
  {
    id: 2,
    title: "DCSS Test",
    description:
      "touts les grands sites web utilisent une page pour se connecter et s’enregistrer, c’est pour cela je mets en évidence ma capacité à en developper une",
    image: "/projects/football-prediction.jpg",
    tags: ["UI material", "React", "typeScript", "Login Page"],
    category: "AI",
    featured: true,
    liveUrl: " https://safeelictron.netlify.app",
    githubUrl: "https://github.com/rye852/dcss",
    year: "2024",
  },
  {
    id: 3,
    title: "YoutubeClones",
    description: "pour voir la manipulation des API.",
    image: "/projects/car-price.jpg",
    tags: ["UI material", "React", "typeScript", "API"],
    category: "AI",
    featured: true,
    liveUrl: "https://jrtube.netlify.app",
    githubUrl: "https://github.com/rye852/Youtube-Clone",
    year: "2025",
  },
]
